spring:
 profiles: 
  active: 
   - dev
---
spirng: 
 profiles: dev	#开发环境
 application: 
  name: microservicecloud-config-yjt-dev
---
spring:
 profiles: test	#测试环境
 application:
  name: microservicecloud-config-yjt-test
